[package]
name = "bscp-channelserver"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "bscp-channelserver"
path = "src/main.rs"

[dependencies]
bscp-common = { path = "../common" }
axum.workspace = true
axum-extra.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true

[dev-dependencies]
reqwest.workspace = true
